---
title: "DEseq"
author: "Johan"
date: "10/10/2017"
output: html_document
---


```{r load deseq library , include=TRUE}

# If not loaded before do this
#source("http://bioconductor.org/biocLite.R")
#biocLite("DESeq2")

library(DESeq2)

```


### Load the data
```{r load the count table library , include=TRUE}

# If not loaded before do this
#source("http://bioconductor.org/biocLite.R")
#biocLite("DESeq2")

# Load the data where you want it 
counts1 <- read.delim("../../data/countTable_1.tab.txt", header = FALSE, row.names = 1)
colnames(counts1) = c("CT_1_S1_L001_R1_0012", 
"CT_2_S2_L001_R1_0012",
"CT_3_S3_L001_R1_0012", 
"CT_7_S7_L001_R1_0012", 
"CT_8_S8_L001_R1_0012", 
"CT_9_S9_L001_R1_0012", 
"WT_10_S10_L001_R1_0012", 
"WT_11_S11_L001_R1_0012", 
"WT_12_S12_L001_R1_0012", 
"WT_4_S4_L001_R1_0012", 
"WT_5_S5_L001_R1_0012", 
"WT_6_S6_L001_R1_0012")

count1Metadata <- read.table("countTable_1_metafile.txt", sep = " ", header = TRUE)
counts1 = counts1[ , as.character(count1Metadata$BamfileName)]



```


```{r put the data in the deseq  , include=TRUE}

# asing the samples into samples 

ds <- DESeqDataSetFromMatrix(countData=counts1, colData=count1Metadata, design=~Time+Type)

colnames(ds) <- count2Metadata$sampleName


```


## Apply regularized-log transform to counts

```{r log transform , include = TRUE }
rld <- rlogTransformation(ds)


```


## Principal component analysis

```{r plot pca after normalisation , include = TRUE }
plotPCA(rld, intgroup=c("Type","Time"))
```


```{r plot a heat map of all genes  , include = TRUE  }
## Heatmap of sample distances
library("gplots")   # If this fails, run: install.packages("gplots")
library("RColorBrewer")
sampleDists <- dist(t(assay(rld)))
sampleDistMatrix <- as.matrix( sampleDists )
colours <- colorRampPalette(rev(brewer.pal(9, "Blues")))(255)
heatmap.2(sampleDistMatrix, trace="none", col=colours)


````



```{r plot a heat map of most variable genes  , include = TRUE  }

## Heatmap of 35 most variable genes
library("genefilter")
topVarGenes <- head(order(rowVars(assay(rld)), decreasing=TRUE), 35)
heatmap.2(assay(rld)[topVarGenes, ], scale="row",
trace="none", dendrogram="column", margins=c(5, 10),
col=colorRampPalette(rev(brewer.pal(9, "RdBu")))(255))

```



```{r Run differential expression analysis  , include=TRUE}


ds <- DESeq(ds, )


# and get the result
res <- results(ds, c("Tissue","Pod wall","Seed"))

```



```{r Only keep reeds that are significant , include = TRUE }
sum( is.na(res$padj) )
res <- res[ ! is.na(res$padj), ]
nrow(res)



sig <- res[ which(res$padj < 0.01), ]

# and order them so that the top is first
sig <- sig[ order(sig$padj), ]

# and view them
sig <- as.data.frame(sig)
head(sig, n=20)

```

```{r Plot the diff exp distribution , include = TRUE }


plotMA(ds)


```

## Apply regularized-log transform to counts

```{r log transform , include = TRUE }
rld <- rlogTransformation(ds)


```


## Principal component analysis

```{r plot pca after normalisation , include = TRUE }
plotPCA(rld, intgroup=c("Tissue","time"))
```


```{r plot a heat map of all genes  , include = TRUE  }
## Heatmap of sample distances
library("gplots")   # If this fails, run: install.packages("gplots")
library("RColorBrewer")
sampleDists <- dist(t(assay(rld)))
sampleDistMatrix <- as.matrix( sampleDists )
colours <- colorRampPalette(rev(brewer.pal(9, "Blues")))(255)
heatmap.2(sampleDistMatrix, trace="none", col=colours)


````



```{r plot a heat map of most variable genes  , include = TRUE  }

## Heatmap of 35 most variable genes
library("genefilter")
topVarGenes <- head(order(rowVars(assay(rld)), decreasing=TRUE), 35)
heatmap.2(assay(rld)[topVarGenes, ], scale="row",
trace="none", dendrogram="column", margins=c(5, 10),
col=colorRampPalette(rev(brewer.pal(9, "RdBu")))(255))

```

